### PR TITLE
fix(lexer): private identifier can start with escaped unicode

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by 3cp** [comment]
✘ 8 invalid programs did not produce a parsing error (without a corresponding entry in the whitelist file)

Details:
   8 invalid programs did not produce a parsing error (without a corresponding entry in the whitelist file):
   language/expressions/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwj-error.js (default)
   language/expressions/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwj-error.js (strict mode)
   language/expressions/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwnj-error.js (default)
   language/expressions/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwnj-error.js (strict mode)
   language/statements/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwj-error.js (default)
   language/statements/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwj-error.js (strict mode)
   language/statements/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwnj-error.js (default)
   language/statements/class/elements/syntax/early-errors/grammar-privatename-identifier-invalid-zwnj-error.js (strict mode)

**Comment by 3cp** [comment]
Ready for review.

**Comment by 3cp** [comment]
The rest of the whitelist have lots of (1) class private property, and (2) destructuring patterns. They look troublesome :(

I am not a fan of adding too many features to a language. It's making JS syntax and lexical analysis way too complex.

**Review by fisker — APPROVED** [review]
Great!

**Pull request merged**
