### PR TITLE
add pkg.type and pkg.exports

### PR DESCRIPTION
**Pull request by Rich-Harris**
Hi! 

At present, if you import Meriyah as a module in the context of a bundler like Rollup, you have to use named imports otherwise the bundler will complain that there is no default export:

```js
// my-lib/src/index.js
import { parseModule } from 'meriyah';
```

But if you run `my-lib/src/index.js` directly in Node (e.g. because your test suite imports it) then the reverse is true: Node thinks Meriyah is a CommonJS module and thus _only_ has a default export.

This PR adds two things to package.json — a [`"type": "module"` field](https://nodejs.org/api/packages.html#packages_type) and an [`"exports": {...}` map](https://nodejs.org/api/packages.html#packages_exports). The first of these tells Node that the `meriyah` package is ESM rather than CommonJS, which means `import { parseModule }` behaves equivalently whether it's encountered by Node or a bundler. The second is what Node (and bundlers) use to resolve `meriyah` to `/path/to/meriyah/dist/meriyah.esm.js` (or the CommonJS equivalent, if using `require`).

It also renames the `prettier.config.js` and `.eslintrc.js` files to use a `.cjs` extension, since they will otherwise be treated as modules because of this change (and ESLint and Prettier aren't ready for that). It also adds a `package.json` inside the `scripts` directory that causes those files to continue to be treated as CommonJS.

Note that while this will improve compatibility in the future, it is a breaking change so would need a major version bump. Thanks for considering!

### CODE REVIEW

**Comment by 3cp** [comment]
Interesting, is this the way to support esm in node v12+ without breaking node v10 and before?

**Comment by Rich-Harris** [comment]
(About the failing `npm run lint`: it appears that ESLint is smart enough to detect that the package has `"type": "module"` and configure itself accordingly to error on `require` etc, but not smart enough to detect that there's a `scripts/package.json` that overrides it... I guess the only solution barring an ESLint fix would be to convert everything in `scripts.js` to ESM as well. I can do that if you agree)

**Comment by Rich-Harris** [comment]
> Interesting, is this the way to support esm in node v12+ without breaking node v10 and before?

Exactly, yes. For anyone doing this...

```
const meriyah = require('meriyah');
```

...nothing will change, whether they're using Node 10 or Node 15. This change only affects people who are using Node 12 or above and want to use `import` syntax without a build step.

**Review by KFlash — APPROVED** [review]

**Comment by 3cp** [comment]
Updating scripts to esm means requiring nodejs12+ to build. Maybe we just skip scripts folder for eslint? @KFlash ?

@Rich-Harris thanks for showing this neat trick. I was quite upset about nodejs esm support because it is not backward compatible.

**Comment by 3cp** [comment]
Oh, it's using .cjs on eslint on prettier, already requiring nodejs v12+ to build.

**Comment by 3cp** [comment]
I will skip the folder for eslint.

**Comment by Rich-Harris** [comment]
thanks so much for the quick response!

**Comment by 3cp** [comment]
Will take few days before next release. Currently adding #168.

**Comment by 3cp** [comment]
@Rich-Harris I got trouble to consume meriyah in commonjs code.

In a folder, I do
```
npm i ../../github/meriyah
node test.cjs
```

The test.cjs is just
```js
const {parseScript} = require('meriyah');
console.log(parseScript('a=1'));
```

Nodejs v14.15.4 complains
```
huocp@chunpengs-mbp ~/p/t> node test.cjs
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/huocp/github/meriyah/dist/meriyah.umd.js
require() of ES modules is not supported.
require() of /Users/huocp/github/meriyah/dist/meriyah.umd.js from /Users/huocp/playground/t/test.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename meriyah.umd.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/huocp/github/meriyah/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/huocp/playground/t/test.cjs:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
```

It seems thinking the `exports.require: './dist/meriyah.umd.js'` is an ESM module??

**Comment by 3cp** [comment]
Ok, `exports.require: './dist/meriyah.umd.cjs'` and copy `meriyah.umd.js to meriyah.umd.cjs` fixed the issue.

**Comment by Rich-Harris** [comment]
Ah, of course — apologies for missing that, good catch!

**Comment by 3cp** [comment]
v4.1.1 should work as expected.

**Pull request merged**
