### PR TITLE
feat: remove option "directives"

### PR DESCRIPTION
**Pull request by 3cp**
BREAKING CHANGE: remove option "directives" as directives is in ECMA spec, and ESTree spec. No point to make it an optional feature.

### CODE REVIEW

**Review by fisker — APPROVED** [review]

**Comment by 3cp** [comment]
Mind me releasing v6?

**Comment by fisker** [comment]
Go

**Comment by 3cp** [comment]
FYI, I have greatly simplified our gh-pages, removed all toolchain, use static html file with native esm loading.

https://github.com/meriyah/meriyah/tree/gh-pages

**Comment by fisker** [comment]
Looks great!

**Comment by 3cp** [comment]
And use `@babel/code-frame` to highlight error location in code :-)

**Pull request merged**
