### PR TITLE
feat(parser): add .range: [start, end] to improve compatibility with other ESTree tools

### PR DESCRIPTION
**Pull request by 3cp**
Related to #81 

-----

Code change is in first commit, note src/parser.ts was formatted by prettier due to pre-commit hook.

### CODE REVIEW

**Comment by KFlash** [comment]
@3cp Great work! If you have time, interested to be part of a for now private and insane project? It will change everything known about tooling and more.

**Comment by 3cp** [comment]
Can you merge and get a release?

**Comment by 3cp** [comment]
The v1.9.14 didn't include this feature. cc @mamaniv

**Comment by KFlash** [comment]
Released v1.9.15. Is the feature included now?

**Comment by 3cp** [comment]
It is. Thx!

**Pull request merged**
