### PR TITLE
fix(parser): fix import.meta check, fix await check

### PR DESCRIPTION
**Pull request by 3cp**
There is still #337 not fixed. But I will live with it for now.

### CODE REVIEW

**Comment by 3cp** [comment]
Added another fix for duplicated proto in parenthesis.

**Comment by 3cp** [comment]
Rest in whitelist are bit hard, except json-invalid.js is out of scope for meriyah.
@fisker let me know if there is anything else you want before I release meriyah v6.

**Comment by fisker** [comment]
> Rest in whitelist are bit hard

I think it's fine to ignore some edge cases.

> if there is anything else you want before I release meriyah v6.

I don't have things to do now.

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
One second

**Comment by fisker** [comment]
Maybe we can fix this https://github.com/meriyah/meriyah/blob/c9857c6f24f64a460cccbbc87249720ee0e8e30d/test/test262-parser-tests/unsupported-features.txt#L4 before release v6?

**Comment by 3cp** [comment]
That one is impossible with meriyah.

meriyah doesn't parse regexp syntax tree, we uses JS runtime to validate regexp. That feature is not implemented in V8 and browsers. So it always pops out as error (before it's widely implemented).

**Comment by 3cp** [comment]
I will hold v6 release for few weeks.

**Comment by fisker** [comment]
I'm aware that we doesn't parse regular expressions, I thought Nide.js already support, sorry.

Anyway, if we are not going to Implement parse logic for it, how do you think the following options

1. Find a small lib for it.
1. Skip parsing (maybe under a `flag`).
1. Let user pass a function to parse.

So we will not relay on runtime

**Comment by 3cp** [comment]
Wait a minute, Chrome added support of it in May 2024.
https://caniuse.com/mdn-javascript_regular_expressions_named_capturing_group_duplicate_named_capturing_groups

Nodejs will have it soon with next v8.

**Comment by fisker** [comment]
I still think we should not relay on runtime.

**Comment by 3cp** [comment]
I agree, but not going to do anything about it now. That's quite some work.

In addition parsing regexp will make meriyah considerably bigger I think.
The regexp-duplicate-named-groups (duplicated name is allowed in separate branches) requires additional lexical analysis.

**Comment by fisker** [comment]
What's your opinion for these options https://github.com/meriyah/meriyah/pull/338#issuecomment-2351047474

**Comment by 3cp** [comment]
Probably 1 or write ourself.

**Comment by 3cp** [comment]
Looks quite a lot of code.
https://github.com/acornjs/acorn/blob/master/acorn/src/regexp.js

**Pull request merged**
