### PR TITLE
Revert "Fix tracking of parser location regardless of line-ending format"

### PR DESCRIPTION
**Pull request by KFlash**
Reverts meriyah/meriyah#49

### CODE REVIEW

**Comment by KFlash** [comment]
@lawrence-dol Can you fix this before merging?

1. Lines for `for([{a=0}] of b);`, `for (const {j} of x) { var [foo] = [j] }` and ` of = 42` plus 92 more tests have wrong line number. The line is `0`, but should be `1`

**Comment by KFlash** [comment]
@lawrence-dol `function isLineBreakPair` is missing types

**Comment by lawrence-dol** [comment]
I'll look into it after work tomorrow; it's 01:37 for me and I'm off to bed.

**Comment by KFlash** [comment]
Ok. Gn :)

**Comment by KFlash** [comment]
@aladdin-add Any idea why all tests pass in previous PR in CircleCI when they actually failed? Same tests locale and 94 tests was broken there. So I was forced to revert the merge.

**Comment by aladdin-add** [comment]
seems circleci didn't run on PRs.
image

**Comment by aladdin-add** [comment]
might related: https://circleci.com/changelog/#granular-control-over-fork-pr-builds

**Comment by KFlash** [comment]
Could you try to fix this? You have permissions to it

**Comment by aladdin-add** [comment]
it seems not ture. 😂
image

**Comment by KFlash** [comment]
@aladdin-add I don't get it? You had the same status since day 1

admin

**Comment by aladdin-add** [comment]
not sure what happened -- I just had the permission, and it should be working now!  🎉
image

**Comment by KFlash** [comment]
Thanks! Sounds good now :)

**Comment by KFlash** [comment]
@lawrence-dol @aladdin-add What do you think about [this gist](https://gist.github.com/KFlash/64cbba3be2b5180567f5e0fc7ddd1721). Just an experiment, and little harder to implement. Each column value has to be subtracted with either `startIndex` or `endIndex`. But it operators on a locale boolean so should be fast.

**Comment by KFlash** [comment]
@lawrence-dol I'm merging this PR. Just open a new PR with your changes when and if you have time. Thanks!

**Pull request merged**
