### PR TITLE
Performance upgrades

### PR DESCRIPTION
**Pull request by GuyLewin**

### CODE REVIEW

**Comment by GuyLewin** [comment]
Thanks! I saw your work on 2.0, it’s awesome. It’ll take me some time to port

**Comment by KFlash** [comment]
Yeah in current 2.0 I focused on tweaking the scanner code. Note that a local boolean turns out to be faster. You see how I use it in that source.

**Comment by KFlash** [comment]
@GuyLewin Just noticed it. See [this lines](https://github.com/GuyLewin/meriyah/blob/2c003d4ca82b1f551da9bf3c508b3af2717026c3/src/lexer/comments.ts#L109-L115) . You can combine this into one single "else" and only modify the state once.

**Comment by GuyLewin** [comment]
@KFlash yeah but then in case `parser.currentChar ^ Chars.LineSeparator`- we're setting `state` twice. Right now we're setting it once but the code is semi-duplicate.

**Comment by KFlash** [comment]
Any possibility we could ship the `parser.currentChar` and set the value right before return? In the 2.0 code I'm not caching anything. Look at the multiline comment code there. I improved it even further.

**Pull request merged**
