### PR TITLE
perf(lexer): improved lexer perf

### PR DESCRIPTION
**Pull request by KFlash**

### CODE REVIEW

**Review by 3cp — APPROVED** [review]

**Comment by KFlash** [comment]
@3cp The lexer can be optimized some more, but is it worth it? Still faster than Acorn.

The picture below is from my own private parser code too show off how fast you actually can get a JS parser ;)

experiment

**Comment by 3cp** [comment]
That's insane, another difference implementation than escaya?

**Comment by KFlash** [comment]
Yeah the parser used there is my own private code and part of my language. The trick is to get the whitespace and token dispatch code optimized correctly. 
It only does basic parsing and output an compressed AST. The most "heavy" stuff are done in the binder, evaluator and type checking.

**Comment by KFlash** [comment]
Here is an subset of the parser to backup my claim about the benchmark :) All you need to do is `x.parseScript(CODE)`;

https://gist.github.com/KFlash/26926a92e90029622e7c371158963e9e

**Comment by KFlash** [comment]
@3cp The main trick is to limit the while loops and prevent infinite loops. That way the parser will continue to parse / stay alive even if invalid syntax. Throwing an error is expensive :)

See "recovery mode" in Escaya for an idea regarding that. My private parser uses an improved  "recovery mode" with incremental support.

In Meriyah we may be able to optimize some of the loops etc, but I think the token bitwise masks can't be swapped around?

**Pull request merged**
