### PR TITLE
fix(lexer): \8 \9 are acceptable in web compatibility mode

### LINKED ISSUE #137: Can't parse `"\8"`
```js
const a = "\8";
```

This is valid code.

### PR DESCRIPTION
**Pull request by 3cp**
closes #137

### CODE REVIEW

**Comment by KFlash** [comment]
Escaped numbers in the grammar is octals ( 0 - 7).  So this shouldn't be allowed. Test it on ASTExplorer with different parsers. Both in sloppy and module goal.

**Comment by 3cp** [comment]
No js implementation complain it now. I even checked back on nodejs v0.10.48, it was fine too.
https://github.com/tc39/test262-parser-tests/issues/25

Might be a spec change sometime in the past. The above issue mentioned Annex B.1.2.

**Comment by 3cp** [comment]
Almost any invalid escape char is fine in the spec.
http://www.ecma-international.org/ecma-262/11.0/index.html#prod-NonEscapeCharacter

**Comment by 3cp** [comment]
I saw many parsers reject it on https://astexplorer.net. But also few accept it, for example typescript.

**Comment by KFlash** [comment]
Then put it under a AnnexB flag? Typescript accept almost everything on ASTExplorer.

**Comment by 3cp** [comment]
Isn't AnnexB part of ecma standard. Nodejs accepts it in both strict and non-strict modes.

**Comment by KFlash** [comment]
All parsers supports AnnexB out of the box. Meriyah have an option to turn that off.

**Comment by 3cp** [comment]
I didn't see the flag in meriyah code, you might be thinking about another parser of yours.

**Comment by KFlash** [comment]
https://github.com/meriyah/meriyah/blob/master/src/common.ts#L19

**Comment by KFlash** [comment]
Off topic. The `Context` is too long. It already reached `31` and you can risk it turns into negative numbers with 31 and higher.

**Comment by 3cp** [comment]
I didn't know webcompat means annex b in meriyah. Will update.

**Comment by KFlash** [comment]
"Additional ECMAScript Features for Web Browsers" = webcompat = AnnexB

**Review by KFlash — APPROVED** [review]

**Pull request merged**
